default_platform(:ios)

APP_IDENTIFIER = "com.kent.quiz.samgukMaster"
APP_VERSION    = "1.0.0"
API_KEY_ID     = "33P5W93GJQ"
API_ISSUER_ID  = "ed28e2d3-ce1d-4d24-8e58-373132e4b554"
API_KEY_PATH   = File.expand_path("AuthKey_33P5W93GJQ.p8", __dir__)
APPLE_ID       = "sukhaverse@gmail.com"
TEAM_ID        = "KUDC7C6Z9H"
FLUTTER_ENV    = "env -u GEM_HOME -u GEM_PATH -u RUBYOPT -u RUBYLIB -u BUNDLE_BIN_PATH -u BUNDLE_GEMFILE"

platform :ios do
  desc "App Store Connect에 앱 등록"
  lane :create_app do
    produce(
      username: APPLE_ID,
      app_identifier: APP_IDENTIFIER,
      app_name: "Three Kingdoms Quiz",
      language: "en-US",
      app_version: APP_VERSION,
      sku: APP_IDENTIFIER,
      platforms: ["ios"],
      team_id: TEAM_ID
    )
  end

  desc "TestFlight 배포"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: API_KEY_ID,
      issuer_id: API_ISSUER_ID,
      key_filepath: API_KEY_PATH,
      duration: 1200,
      in_house: false
    )

    begin
      build_num = latest_testflight_build_number(
        api_key: api_key,
        app_identifier: APP_IDENTIFIER
      ) + 1
    rescue
      build_num = 1
    end

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "ios/Runner.xcodeproj",
      team_id: TEAM_ID
    )

    sh("cd .. && #{FLUTTER_ENV} flutter pub get")
    sh("cd .. && #{FLUTTER_ENV} flutter build ipa --release --build-name #{APP_VERSION} --build-number #{build_num} --export-options-plist=fastlane/ios_export.plist")

    ipa = Dir[File.expand_path("../build/ios/ipa/*.ipa", __dir__)].max_by { |path| File.mtime(path) }
    UI.user_error!("IPA not found in build/ios/ipa") unless ipa

    upload_to_testflight(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER,
      ipa: ipa,
      skip_waiting_for_build_processing: true
    )
  end
end
